"""
`ausers` admin for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.contrib.auth.admin import UserAdmin as UA

from ausers.models import (Customer, Region, RouteEmployee, RouteOfficer,
                           TicketEmployee, TicketOfficer, Woreda, Zone, Company)


@admin.register(Customer)
class CustomerAdmin(UA):
    """ Extended UserAdmin to included phone_number and is_verified to admin. """

    ordering = ("first_name", "last_name")
    list_display = ("first_name", "last_name", "sex", "phone_number", "is_verified")
    fieldsets = (
        (None, {"fields": ("password",)}),
        ("Personal info", {"fields": ("first_name", "last_name", "phone_number")}),
        ("Address", {"fields": ("region", "zone", "woreda")}),
        (
            "Permissions",
            {"fields": ("work_on", "is_verified", "groups", "user_permissions")},
        ),
        ("Important dates", {"fields": ("last_login", "date_joined")}),
    )
    add_fieldsets = (
        ("Personal info", {"fields": ("first_name", "last_name")}),
        ("Address", {"fields": ("region", "zone", "woreda")}),
        (
            None,
            {
                "classes": ("wide",),
                "fields": ("phone_number", "password1", "password2"),
            },
        ),
    )
    filter_horizontal = ("groups", "user_permissions", "work_on")
    search_fields = ("phone_number", "first_name", "last_name")


admin.site.register(Region)
admin.site.register(Zone)
admin.site.register(Woreda)
admin.site.register(Company)
admin.site.register(get_user_model(), UA)
admin.site.register(TicketOfficer, UA)
admin.site.register(RouteOfficer, UA)
admin.site.register(RouteEmployee, UA)
admin.site.register(TicketEmployee, UA)
