"""
`ausers` admin for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as UA

from ausers.models import Customer, Region, Woreda, Zone


@admin.register(Customer)
class CustomerAdmin(UA):
    """ Extended UserAdmin to included phone_number and is_verified to admin. """

    ordering = ("first_name", "last_name")
    list_display = ("first_name", "last_name", "sex", "phone_number", "is_verified")
    fieldsets = (
        (None, {"fields": ("password",)}),
        ("Personal info", {"fields": ("first_name", "last_name", "phone_number")}),
        ("Address", {"fields": ("region", "zone", "woreda")}),
        ("Permissions", {"fields": ("is_verified", "groups", "user_permissions")}),
        ("Important dates", {"fields": ("last_login", "date_joined")}),
    )
    add_fieldsets = (
        ("Personal info", {"fields": ("first_name", "last_name")}),
        ("Address", {"fields": ("region", "zone", "woreda")}),
        (
            None,
            {
                "classes": ("wide",),
                "fields": ("phone_number", "password1", "password2"),
            },
        ),
    )
    search_fields = ("phone_number", "first_name", "last_name")


admin.site.register(Region)
admin.site.register(Zone)
admin.site.register(Woreda)
