"""
`ausers` apps for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""

from django.apps import AppConfig


class AusersConfig(AppConfig):
    name = 'ausers'
