"""
`ausers` models for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""
import json

from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    """ Custome User Model with to generalizer all users of platform. """
    pass

class Address(models.Model):
    """ Implement common address attributes
            - Region
            - Zone
            - Woreda
            - House Number
    """
    region = models.CharField(max_legth=6)
    zone = models.CharField(max_legth=6)
    woreda = models.CharField(max_legth=6)
    house_number = models.CharField(max_legth=6)
    
    class Meta:
        abstract = True

class Customer(User):
    pass
