"""
`ausers` models for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""
import json

from django.db import models

from django.contrib.auth.models import AbstractUser

from smart_selects.db_fields import ChainedForeginKey

class User(AbstractUser):
    """ Custome User Model with to generalizer all users of platform. """
    SEX = (
        ('M', ('Male')),
        ('F', ('Female'))
    )
    sex = models.CharField(max_length=2, choices=SEX)

class Region(models.Model):
    name = CharField(max_length=255)

class Zone(models.Model):
    region = models.ForeginKey(Region, on_delete=models.CASCADE)
    name = CharField(max_length=255)

class Woreda(models.Model):
    zone = models.ForeginKey(Zone, on_delete=models.CASCADE)
    name = CharField(max_length=255)

class Address(models.Model):
    """ Implement common address attributes
            - Region
            - Zone
            - Woreda
            - House Number
    """
    region = models.ForeginKey(Region, on_delete=models.SET_NULL, null=True)
    zone = ChainedForeginKey(
            Zone,
            chained_field='region',
            chained_models_field='region',
            show_all=False,
        )
    woreda = ChainedForeginKey(
            Woreda,
            chained_field='woreda',
            chained_models_field='woreda',
            show_all=False,
        )
    house_number = models.CharField(max_length=6)

    class Meta:
        abstract = True

class Customer(User):
    pass
