"""
`ausers` urls for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""
from django.urls import include, re_path

from ausers import views
from pages.views import MessageView

messages = {"1": "Password changened successfully."}
urlpatterns = [
    re_path(r"^login/", views.LoginView.as_view(), name="login"),
    re_path(
        r"^password_change/done/$",
        MessageView.as_view(message=messages.get("1")),
        name="password_change_done",
    ),
    re_path(
        r"^password_reset/", views.PasswordResetView.as_view(), name="password_reset"
    ),
    re_path(r"^", include("django.contrib.auth.urls")),
    re_path(r"^signup/$", views.SignUpView.as_view(), name="signup"),
    re_path(r"^verify/$", views.VerifyCustomer.as_view(), name="verify-customer"),
]
