"""
`ausers` urls for tena project.

Generated by 'python3 manage.py startapp' using Django 3.1.7.
 * NAME: Wendirad Demelash
 * DATE: April 3, 2021
"""
from django.urls import re_path

from ausers import views

urlpatterns = [
    re_path(r'^signup/$', views.SignUpView.as_view(), name='signup'),
]
